server:
  port: 8086

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/wa_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      connect-timeout: ${REDIS_TIMEOUT}

integration:
  storage-service:
    base-url: ${STORAGE_SERVICE_BASE_URL:http://localhost:8085}
    path: ${STORAGE_SERVICE_PATH:/v1/internal/users/{userId}/dashboard}
    timeout: 5000

aws:
  s3:
    access-key-id: ${AWS_S3_ACCESS_KEY_ID:admin}
    secret-access-key: ${AWS_S3_SECRET_ACCESS_KEY:admin123}
    region: us-east-1
    endpoint:
      internal: ${AWS_S3_ENDPOINT_INTERNAL:http://minio:9000}
      public: ${AWS_S3_ENDPOINT_PUBLIC:http://localhost:9000}
    path-style-access: true
    bucket-name: ${AWS_S3_BUCKET_NAME:health-reports}
    presigned-url-expiration: 3600

jwt:
  secret:
    access: ${JWT_SECRET_ACCESS:Y5ncOVqSI/HnJisBxE0TDsk/3cMP/FbwMDL+elybXkqsmpjNIqbjwCCOM8wTznVkqxeYZqf+ppsr4wzHNt8peA==}

schedule:
  report-deletion:
    cron: ${REPORT_DELETION_CRON:0 0 1 * * SUN}

logging:
  charset:
    console: UTF-8
