server:
  port: 8086

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      connect-timeout: ${REDIS_TIMEOUT}

integration:
  storage-service:
    base-url: ${STORAGE_SERVICE_BASE_URL}
    path: ${STORAGE_SERVICE_PATH}
    timeout: 5000

aws:
  s3:
    access-key-id: ${AWS_S3_ACCESS_KEY_ID}
    secret-access-key: ${AWS_S3_SECRET_ACCESS_KEY}
    region: us-east-1
    endpoint:
      internal: ${AWS_S3_ENDPOINT_INTERNAL}
      public: ${AWS_S3_ENDPOINT_PUBLIC}
    path-style-access: true
    bucket-name: ${AWS_S3_BUCKET_NAME}
    presigned-url-expiration: 3600

jwt:
  secret:
    access: ${JWT_SECRET_ACCESS}

schedule:
  report-deletion:
    cron: ${REPORT_DELETION_CRON}

logging:
  charset:
    console: UTF-8
